# tool.toml

# coc lsp
[[plugins]]
repo = 'neoclide/coc.nvim'
# CocInstall coc-explorer
hook_add = '''
  let g:coc_explorer_global_presets = {
\   'ide' : {
\     'open-action-strategy': 'sourceWindow',
\     'floating-width' : 70,
\   }
\ }
  nmap <space>e :CocCommand explorer --preset ide<CR>
'''

# Vaffle filer
[[plugins]]
repo = 'cocopon/vaffle.vim'

# indent line
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char = '│'
'''

# before_tried
#
# setting for indent guides
# let g:indent_guides_enable_on_vim_startup = 1
# set ts=4 sw=4 et
# let g:indent_guides_start_level = 2
# let g:indent_guides_guide_size = 1


